### ISSUE TITLE
snap "homebridge" has no "configure" hook

### ISSUE THREAD

**Issue by Brockhold** [kubiko/homebridge-snap#1]
I'm currently developing a simple plugin, and I've hit an issue using snap to configure homebridge. According to homebridge.help, it ought to support setting keys. However, when I try this I see the following:
```
$ sudo snap set homebridge opts="-P <path to a plugin>" 
error: cannot perform the following tasks:
- Run configure hook of "homebridge" snap (snap "homebridge" has no "configure" hook)
```
I am able to install/remove my plugin using NPM directly, but I given the response conflicts with the documentation, I suspect this behavior is incorrect.

**Comment by kubiko** [comment]
Hi @Brockhold 
thanks for spotting this, indeed configure hook is missing. Before I will add it, it'd be good to understand your use-case so I can factor for it. As at the moment I have there only two config options, auto package update and nom options.
Is there some particular config feature you would like to have there?

**Comment by Brockhold** [comment]
Hi @kubiko!
Nothing fancy, I was hoping to be able to set homebridge's -P flag and point it at a directory in which I'm developing a plugin. It's a little nicer than repeatedly installing and removing a homebridge plugin as an npm package.

Based on the message printed by `homebridge.help` I expected to be able to set the key "opts" in order to pass a string of launch options to homebridge. I see in glue/bin/config that it's defined, but since there's no configure hook it can't be changed.

**Comment by kubiko** [comment]
@Brockhold sorry I didn't get back earlier. Try snap from edge channel, it should have the fix

**Comment by Brockhold** [comment]
@kubiko Thanks for the fix, apologies for getting back so late.
After using `sudo snap set homebridge opts="-D -P /var/homebridge/homebridge-coffeebutton/" ` (which returns no errors) I then verify by `sudo homebridge.help` and observe that the value for `opts` has correctly changed. So far so good.

However, running `sudo homebridge.manual` to observe console errors, it complains about the values set in opts:
> HOMEBRIDGE_AUTO_UPDATE_NPM_MODULES=on (default value)
> HOMEBRIDGE_OPTS=-D -P /var/homebridge/homebridge-coffeebutton/
> /snap/homebridge/920/bin/homebridge-read-settings: line 18: export: \`-P\`: not a valid identifier
> /snap/homebridge/920/bin/homebridge-read-settings: line 18: export: \`/var/homebridge/homebridge-coffeebutton/\`: not a valid identifier


I may not be using this correctly.

**Comment by kubiko** [comment]
@Brockhold for start path is wrong, homebridge snap will not have access to `/var/homebridge/homebridge-coffeebutton/`
That extra option is very basic, only adds extra option to any npm call, so you have to make sure it does not break something else.
Also if you just need logs then why not to use already existing logs of homebridge?

**Comment by kubiko** [comment]
Closing this issue for no feedback.
