### ISSUE TITLE
Most recent revision broke my installation

### ISSUE THREAD

**Issue by Kentzo** [kubiko/homebridge-snap#3]
Got `1.1.4-2023-12-2` automatically installed ~3 days ago and it broke my installation: Homebridge failed to start with no useful information in the logs, just:

```
Dec 29 23:09:16 Kentzo-Pi systemd[1]: Started Service for snap application homebridge.homebridge.
Dec 29 23:09:16 Kentzo-Pi homebridge.homebridge[11055]: ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be>
Dec 29 23:09:16 Kentzo-Pi homebridge.homebridge[11055]: HOMEBRIDGE_AUTO_UPDATE_NPM_MODULES=off
Dec 29 23:09:16 Kentzo-Pi homebridge.homebridge[11055]: HOMEBRIDGE_OPTS= (default value)
Dec 29 23:09:16 Kentzo-Pi homebridge.homebridge[11055]: ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be>
Dec 29 23:09:16 Kentzo-Pi homebridge.homebridge[11090]: ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be>
Dec 29 23:09:17 Kentzo-Pi homebridge.homebridge[11090]: ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be>
Dec 29 23:09:18 Kentzo-Pi homebridge.homebridge[11090]: [12/29/2023, 11:09:18 PM] [HB Supervisor] Homebridge Storage Path: /var/snap/homebridge/common
Dec 29 23:09:18 Kentzo-Pi homebridge.homebridge[11090]: [12/29/2023, 11:09:18 PM] [HB Supervisor] Homebridge Config Path: /var/snap/homebridge/common/config.json
Dec 29 23:09:18 Kentzo-Pi homebridge.homebridge[11090]: [12/29/2023, 11:09:18 PM] [HB Supervisor] Logging to /var/snap/homebridge/common/homebridge.log
Dec 29 23:09:28 Kentzo-Pi systemd[1]: snap.homebridge.homebridge.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 23:09:28 Kentzo-Pi systemd[1]: snap.homebridge.homebridge.service: Failed with result 'exit-code'.
Dec 29 23:09:29 Kentzo-Pi systemd[1]: snap.homebridge.homebridge.service: Scheduled restart job, restart counter is at 5.
Dec 29 23:09:29 Kentzo-Pi systemd[1]: Stopped Service for snap application homebridge.homebridge.
```

Over and over again.

Revert to `1.7.0-2023-11-04` immediately fixed it.

**Comment by Kentzo** [comment]
Looks like new version just ignores `config.json`.

I wonder if that's related to switching to the hb-service runner (via start.sh) because I disable homebridge-config-ui-x:

```json
{
...
    "disabledPlugins": [
        "homebridge-config-ui-x"
    ],
...
}
```

**Comment by kubiko** [comment]
@Kentzo there is probably more reasons here.
I have done major rework of the snap, mainly to move to the use of the deb release from the provided PPA.
That also explains the drop in the version number as now it's deb version, vs `homebridge` version before. This is favourable, as snap contains `homebridge-config-ui-x` as well as `homebridge`.  Plus by using deb, hopefully, I can provide a more seamless experience going forward.

Unfortunately, all those changes meant that I had introduced one more major change, installed plugins were global installs before and I was copying also bundle packages from snap to the writable path, not ideal storage wise.
Now homebdridge snap has global npm install and all the plugins are local installs in `SNAP_COMMON`. This is now aligned with the deb version behaviour.
I provided some auto migration steps, where I re-install all the same packages from the existing install as local packages.
But ultimately if you have anything more complex, the best is to save the config and install plugins through webui and then restore the custom config.

On the plus side, webui now functions more reliably.

And to your question, there is only one snap service which is webui. It seems like the lifecycle of the `homebridge` process is driven by `homebridge-config-ui-x`, as it's able to restart `homebridge` without interrupting webui and can handle broken `config.json` as well.

**Comment by Kentzo** [comment]
I understand the file shuffling, yet I'm still puzzled by the behavior I observe.

I opened a shell into the snap and tried to run it manually via start.sh with only one modification: added `--stdout`. In the output I see that it tries and fails to bind on the 5353 port (mDNS).

```
root@Kentzo-Pi:~# /snap/homebridge/current/opt/homebridge/start.sh --allow-root --stdout
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
[1/2/2024, 12:37:35 AM] [HB Supervisor] Homebridge Storage Path: /var/snap/homebridge/common
[1/2/2024, 12:37:36 AM] [HB Supervisor] Homebridge Config Path: /var/snap/homebridge/common/config.json
[1/2/2024, 12:37:36 AM] [HB Supervisor] OS: Linux 5.10.103-v7+ arm
[1/2/2024, 12:37:36 AM] [HB Supervisor] Node.js v18.18.2 /snap/homebridge/3489/opt/homebridge/bin/node
[1/2/2024, 12:37:36 AM] [HB Supervisor] Homebridge Path: /var/snap/homebridge/common/node_modules/homebridge/bin/homebridge
[1/2/2024, 12:37:36 AM] [HB Supervisor] UI Path: /snap/homebridge/3489/opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[1/2/2024, 12:37:43 AM] [Homebridge UI] Homebridge UI v4.53.0 is listening on :: port 8080
Error: bind EADDRINUSE 0.0.0.0:5353
    at node:dgram:364:20
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

which is wrong as my config.json (at /var/snap/homebridge/common/config.json) contains:

```json
    "bridge": {
...
        "advertiser": "avahi",
        "bind": [
            "vlan-main"
        ]
    },
```

Did you test running new snap with disabled `homebridge-config-ui-x`? In my case it's very unnecessary and I don't want to bother with Homebridge's credentials.

**Comment by kubiko** [comment]
if you are using avahi as an advertiser, make sure to connect avahi-control
On Ubuntu Core:
- install avahi snap and connect `avahi-control`: `snap connect homebridge:avahi-control avahi:avahi-control`
On Classic systems:
- install avahi (either as deb or as snap, but not both!)
- in case of the deb install, connect as `snap connect homebridge:avahi-control`

Without this, I'd expect to see some aa denials in the journal.

**Comment by Kentzo** [comment]
I think my snap config is correct. Again, it worked before the update 3 days ago:

```
pi@Kentzo-Pi:/var/snap/homebridge/common $ snap connections --all
Interface      Plug                      Slot            Notes
avahi-control  homebridge:avahi-control  :avahi-control  manual
log-observe    homebridge:log-observe    -               -
network        homebridge:network        :network        -
network-bind   homebridge:network-bind   :network-bind   -
ppp            homebridge:ppp            -               -
serial-port    homebridge:serial-port    -               -
```

What homebridge error indicates is that it ignored both the "bridge.advertiser" option (it attempted to bind 5353) and "bridge.bind" (it attempt to bind on 0.0.0.0 rather than this specific interface).

**Comment by kubiko** [comment]
I would need to see aa denials to see what could be happening there. hard to say from here. Though the fact it worked before is a bit strange.

**Comment by Kentzo** [comment]
Perhaps the new wrapper (homebridge-config-ui-x's hb-service) sees that it's being run for the first time and as a result runs homebridge in a way that ignores config.json?

**Comment by kubiko** [comment]
it does clear config migrated, so ensure that you have it set correctly.

**Comment by Kentzo** [comment]
This is `/var/snap/homebridge/common` after update:

```
drwxr-xr-x   2 root root 4.0K Aug 27 13:41 accessories
-rw-r--r--   1 root root  351 Aug 27 13:01 auth.json
drwxr-xr-x   4 root root 4.0K Nov 29 03:06 backups
-rw-r--r--   1 root root 3.1K Jan  2 00:39 config.json
-rw-r--r--   1 root root  639 Jan  2 00:09 homebridge.log
drwxr-xr-x 350 root root  12K Jan  2 00:08 node_modules
drwxr-xr-x   5 root root 4.0K Nov 28 13:07 .npm
-rw-r--r--   1 root root  185 Dec 29 23:08 package.json
drwxr-xr-x   2 root root 4.0K Aug 27 13:24 persist
-rw-r--r--   1 root root  293 Aug 27 13:04 .uix-dashboard.json
-rw-r--r--   1 root root   81 Feb  2  2022 .uix-secrets
```

Do you see something amiss here?

**Comment by Kentzo** [comment]
In order to revert to the working version I did the following:

```
snap stop homebridge
snap refresh --hold homebridge
snap revert homebridge --revision 3412

cd /var/snap/homebridge/common
rm -rf .npm node_modules package.json lib/node_modules
mkdir -p bin lib/node_modules
echo "prefix=/var/snap/homebridge/common" > npmrc

snap run homebridge.npm install ... # homebridge plugins
snap start homebridge
```

**Comment by Kentzo** [comment]
The issue ended up being that hb-service, unlike vanilla homebridge, unconditionally listens on 0.0.0.0:5353. My installation of avahi had the `disallow-other-stacks=yes` which prevented homebridge from starting.

For more information see https://github.com/homebridge/homebridge/issues/3077
